### PR TITLE
added GlobalLoader class and login buttons

### PR DESCRIPTION
**Pull request by amgugu111**
Used flutter_spinkit 4.1.2+1
https://pub.dev/packages/flutter_spinkit#-readme-tab-
@aquibbaig please review 
#25 consider this issue 
Haven't integrated firebase yet, will do it in next commit.

### CODE REVIEW

**Comment by amgugu111** [comment]
loader

**Comment by amgugu111** [comment]
loader

**Comment by amgugu111** [comment]
https://www.clounce.com/flutter/loading-screen-in-flutter

Refer to step 4 here

**Comment by aquibbaig** [comment]
@amgugu Please add a better design for the loader. Something like [this](https://codepen.io/sagarsardiwal/pen/eYOGwZa) will be wonderful. It's easy. You can look at #24. I did a similar animation

**Comment by amgugu111** [comment]
Okay will do it tonight

**Pull request closed without merging**
