### PR TITLE
Workflow Change 

### LINKED ISSUE #42: Player name should be final
Ask for the player's name at first and keep it global. Else we will have multiple player names across all the rooms.

### PR DESCRIPTION
**Pull request by StrangeNoob**
- Integrate Facebook Login with State-Management 
- Change in Workflow
- Enable Play Button Feature for Lobby Leader
Fixes #42 
@aquibbaig please check for iOS. 
changeworkflow

### CODE REVIEW

**Comment by StrangeNoob** [comment]
@aquibbaig There are minor Bugs. Can you help me figure out how to fix this?

**Comment by aquibbaig** [comment]
@StrangeNoob What minor bugs?

**Comment by aquibbaig** [comment]
It will take me some time to review.

**Comment by aquibbaig** [comment]
>     * Integrate Facebook Login with State-Management
> 
>     * Change in Workflow
> 
>     * Enable Play Button Feature for Lobby Leader
>       Fixes #42
>       @aquibbaig please check for iOS.
>       changeworkflow

Will be tracked under #90

**Pull request closed without merging**
